use_gpu: False
device: 0
backend: torch
outdir: vFL_gbdt_50_buckets_20_iter_abalone
federate:
  mode: standalone
  client_num: 2
  total_round_num: 30
model:
  type: gbdt_tree
  lambda_: 0.1
  gamma: 0
  num_of_trees: 15
  max_tree_depth: 3
train:
  optimizer:
    lr: 0.5
    # learning rate for xgb model
    eta: 0.5
data:
  root: data/
  type: abalone
  splits: [0.8, 0.2]
  args: [{normalization: False, standardization: False}]
feat_engr:
  scenario: vfl
dataloader:
  type: raw
  batch_size: 5000
criterion:
  type: RegressionMSELoss
trainer:
  type: verticaltrainer
vertical:
  use: True
  key_size: 256
  dims: [6, 10]
  algo: 'gbdt'
  data_size_for_debug: 0
  feature_subsample_ratio: 1.0
  protect_object: 'feature_order'
  protect_method: 'dp'
  protect_args: [ { 'bucket_num': 50}]
eval:
  freq: 1
  best_res_update_round_wise_key: test_loss
  # metrics: ['acc', 'correct']
hpo:
  scheduler: bo_gp
  ss: 'federatedscope/autotune/baseline/vfl_ss.yaml'
  sha:
    budgets: [ 3, 6 ]
    iter: 20
  metric: 'server_global_eval.test_loss'
  working_folder: vFL_gbdt_50_buckets_20_iter_abalone