use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: random_forest
  lambda_: 0.1
  gamma: 0
  num_of_trees: 10
  max_tree_depth: 6
data:
  root: data/
  type: abalone
  splits: [0.8, 0.2]
dataloader:
  type: raw
  batch_size: 4177
criterion:
  type: RegressionMSELoss
trainer:
  type: verticaltrainer
vertical:
  use: True
  dims: [6, 10]
  algo: 'rf'
  data_size_for_debug: 0
  feature_subsample_ratio: 1
  protect_object: 'feature_order'
  protect_method: 'dp'
  protect_args: [ { 'bucket_num': 50 } ]
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss