use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: xgb_tree
  lambda_: 0.1
  gamma: 0
  num_of_trees: 14
  max_tree_depth: 3
data:
  root: data/
  type: abalone
  splits: [0.8, 0.2]
dataloader:
  type: raw
  batch_size: 4177
criterion:
  type: RegressionMSELoss
trainer:
  type: verticaltrainer
train:
  optimizer:
    # learning rate for xgb model
    eta: 0.19
vertical:
  use: True
  dims: [6, 10]
  algo: 'xgb'
  protect_object: 'feature_order'
  protect_method: 'op_boost'
  protect_args: [{'algo': 'global', 'epsilon': 5, 'bucket_num': 50}]
  data_size_for_debug: 0
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss