use_gpu: False
device: 0
backend: torch
federate:
  mode: standalone
  client_num: 2
model:
  type: xgb_tree
  lambda_: 0.1
  gamma: 0
  num_of_trees: 15
  max_tree_depth: 4
data:
  root: data/
  type: blog
  splits: [1.0, 0.0]
dataloader:
  type: raw
  batch_size: 60021
criterion:
  type: RegressionMSELoss
trainer:
  type: verticaltrainer
train:
  optimizer:
    # learning rate for xgb model
    eta: 0.17
vertical:
  use: True
  dims: [140, 280]
  algo: 'xgb'
  data_size_for_debug: 0
eval:
  freq: 3
  best_res_update_round_wise_key: test_loss